# Config file for an example Majora's Mask: Recompiled mod.

# Fields that end up in the mod's manifest.
[manifest]

# Unique ID of this mod. Pick something long enough that it'll never be the same as any other mod.
# The name displayed in the mod management menu is separate from this so this doesn't need to be human readable.
id = "mm_recomp_rando"

# Version of this mod.
version = "1.0.0"

# The name that will show up for this mod in the mod menu. This should be human readable.
display_name = "MMRecompRando"

# The description that will show up when this mod is displayed in the mod menu. This should be human readable.
description =  """
funny zelda rando
move the zelda things around

https://github.com/RecompRando/MMRecompRando"""

# A short description that will show up in this mod's entry in the mod list. This should be human readable and kept short
# to prevent it from being cut off due to the limited space.
short_description = "hey game different now"

# Authors of this mod.
authors = [ "LittleCube", "ThatHypedPerson", "PixelShake92", "Muervo_", "G4M3RL1F3", "dcvz", "CelestialKitsune", "VincentsSin" ]

# ID of the target recomp game.
game_id = "mm"

# Minimum version of the target recomp (e.g. Zelda 64: Recompiled) that this mod can run on.
minimum_recomp_version = "1.2.2"

# Dependency mods. Each entry is the mod's ID and then an optional minimum version of the dependency mod.
dependencies = [
    "RecompExternalPython_API:2.0.0",
    "owls_never_quit:1.0.0",
    "mm_recomp_better_double_sot:1.0.1",
    "mm_recomp_colors:0.5.0",
    "REPY_PopularPythonPackages:1.0.0",
	"mm_recomp_draw_distance:1.3.0"
]

# REPY_PopularPythonPackages found here: https://github.com/LT-Schmiddy/repy_popular_python_packages

# Optional dependency mods. This has the same format as `dependencies`, but the game will still start if dependencies in this
# list aren't present. You can query the presence of a given dependency by using `recomp_is_dependency_met` in recomputils.h.
# Calling a function imported from an optional dependency that isn't present will trigger an error.
optional_dependencies = [

]

# Native libraries (e.g. DLLs) and the functions they export.
native_libraries = [

]

# Inputs to the mod tool.
[inputs]

# Input elf file to generate a mod from.
elf_path = "build/mod.elf"

# Output mod filename.
mod_filename = "mm_recomp_rando"

# Reference symbol files.
func_reference_syms_file = "Zelda64RecompSyms/mm.us.rev1.syms.toml"
data_reference_syms_files = [ "Zelda64RecompSyms/mm.us.rev1.datasyms.toml", "Zelda64RecompSyms/mm.us.rev1.datasyms_static.toml", "rando_syms.toml" ]

# Additional files to include in the mod.
additional_files = [ "thumb.dds" ]

[[manifest.config_options]]
id = "enable_notifications"
name = "Display Notifications"
description = "Sets if you want to be notified when you receive items."
type = "Enum"
options = [ "Disabled", "Enabled" ]
default = "Enabled"

[[manifest.config_options]]
id = "notification_position"
name = "Notification Position"
description = "Sets where incoming item notifications appear on your screen."
type = "Enum"
options = [ "Top Left", "Top Right", "Bottom Left", "Bottom Right" ]
default = "Top Left"

[[manifest.config_options]]
id = "local_notifications"
name = "Show Local Notifications"
description = """Sets if you want to be notified when your player/slot recieves an item.

This is mainly useful to those wanting to play co-op on the same "slot" within a multiworld."""
type = "Enum"
options = [ "Disabled", "Enabled" ]
default = "Disabled"

[[manifest.config_options]]
id = "deathlink"
name = "DeathLink"
description = """- Multiworlds Only -
Sets if you die when other players who also have "DeathLink" enabled die - the reverse is true as well."""
type = "Enum"
options = [ "Disabled", "Enabled" ]
default = "Enabled"

[[manifest.config_options]]
id = "camc_enabled"
name = "Container Appearance Matches Contents"
description = """Sets if the appearance of different containers match the content within them.

The "Show Unchecked" option will set all uncollected container appearances (excluding chests) to be a golden color."""
type = "Enum"
options = [ "Disabled", "Show Unchecked", "Enabled" ]
default = "Enabled"

[[manifest.config_options]]
id = "show_soul_model"
name = "Show Full Models for Souls"
description = "Sets whether or not Soul items display as their in-game model or a generic token."
type = "Enum"
options = [ "Disabled", "Enabled" ]
default = "Enabled"

[[manifest.config_options]]
id = "enemy_drops"
name = "(DEBUG) Replace Enemy Drops"
description = "Enable/Disable random drops from being randomized."
type = "Enum"
options = [ "Disabled", "Enabled" ]
default = "Disabled"

[[manifest.config_options]]
id = "torchsanity"
name = "(DEBUG) Torchsanity"
description = "Enable/Disable Torchsanity."
type = "Enum"
options = [ "Disabled", "Enabled", "Snuffsanity" ]
default = "Disabled"

[[manifest.config_options]]
id = "skip_time"
name = "(DEBUG) Skip Time by Pressing L"
description = "Enable/Disable time being skipped when pressing L to the following options."
type = "Enum"
options = [ "Disabled", "Enabled" ]
default = "Disabled"

[[manifest.config_options]]
id = "time_day"
name = "(DEBUG) Time Day"
description = "The day that time will be skipped to when pressing L."
type = "Number"
min = 0
max = 7
step = 1
precision = 1
percent = false
default = 1

[[manifest.config_options]]
id = "time_hour"
name = "(DEBUG) Time Hour"
description = "The hour that time will be skipped to when pressing L."
type = "Number"
min = 0
max = 23
step = 1
precision = 1
percent = false
default = 12